# Generated by Django 5.2.11 on 2026-02-27 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('norad_id', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ISSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('velocity', models.FloatField()),
                ('visibility', models.CharField(max_length=50)),
                ('timestamp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tracking.satellite')),
            ],
        ),
    ]
